spring.application.name=thdemo
spring.web.resources.add-mappings=false

## mongo configuration
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=thdemo
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=example

## mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/thdemo
spring.datasource.username=root
spring.datasource.password=ornste1n$Mough

## JPA configuration
# disable OSIV due to performance limitations (it removes the springboot initialisation warning)
spring.jpa.open-in-view=false
# update the schema automatically
spring.jpa.hibernate.ddl-auto=update
# show sql queries at terminal
spring.jpa.show-sql=true 

## i18n configuration
spring.messages.basename=lang/messages